### ISSUE TITLE
Doc Request: Update README with more info about config.json

### ISSUE THREAD

**Issue by oybed** [SylvainGa/Garmin-WeeWX#2]
The README states `You need to input the URL to your daily.json file.`, but it's not clear which `daily.json` this is referring to... and a quick google search yields multiple results with (potentially) varying format. Would be great if the README could be updated with some links and/or additional information about which json file / weewx skin this is expecting to be used, or at least the expected format.

**Comment by SylvainGa** [comment]
Hi, the daily.json file that I'm using comes from the Seasons skin. Does this help you?

**Comment by oybed** [comment]
hi there - not really. We are running the latest `4.8.x` release, using the `Seasons` skin, and it doesn't seem to contain a daily.json file (or a template file). 

Here's the skin's link:
https://github.com/weewx/weewx/tree/master/skins/Seasons

And there's no daily.json file (or template) on the server:
```
# cd /etc/weewx/skins/
# find . | grep -i daily 
(empty)
# cd /var/www/html/
# find . | grep -i daily
(empty)
```

**Comment by SylvainGa** [comment]
Sorry, looking for, I remembered it was installed several years ago when I added my weather station to Home Assistant. I followed this post here to install the daily template

https://community.home-assistant.io/t/weather-station-data/58489/12
